version: "3.1"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5656:5432"
    environment:
      PGDATA: ./data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: remix-hono
